--- #YAML:1.0
name: Path-Class
version: 0.03_01
license: perl
distribution_type: module
requires:
  File::Spec: 0
  File::Spec::Mac: 1.3
  overload: 0
recommends: {}
build_requires: {}
conflicts: {}
provides:
  Path::Class:
    file: lib/Path/Class.pm
    version: 0.03_01
  Path::Class::Dir:
    file: lib/Path/Class/Dir.pm
  Path::Class::Entity:
    file: lib/Path/Class/Entity.pm
  Path::Class::File:
    file: lib/Path/Class/File.pm
generated_by: Module::Build version 0.19_03
