---
abstract: 'Cross-platform path specification manipulation'
author:
  - 'Ken Williams <kwilliams@cpan.org>'
build_requires:
  File::Temp: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200000, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Path-Class
requires:
  Cwd: 0
  File::Path: 0
  File::Spec: 0.87
  File::Spec::Mac: 1.3
  File::stat: 0
  IO::Dir: 0
  IO::File: 0
  overload: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Path-Class
  repository: http://perl-path-class.googlecode.com/svn/trunk
version: 0.23
